Jean Halaby
Final Project Milestone #2
11/19/25

This notebook will go over some simple data analysis of my dataset of 2024 Atlantic Divison NBA teams, which was scraped from Basketball Reference.

In [1]:
import pandas as pd
import numpy as np

In [13]:
# Import Dataset
data = pd.read_csv("nba_atlantic_2024.csv")

In [21]:
# Exploring Dataset
data.columns
data.shape

Index(['Unnamed: 0', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P',
       '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'Team'],
      dtype='object')

These just show the basic information that each column will contain and then the rows/columns of the data set.

In [22]:
data.dtypes

Unnamed: 0     object
G             float64
MP             object
FG             object
FGA            object
FG%           float64
3P             object
3PA            object
3P%           float64
2P             object
2PA            object
2P%           float64
FT             object
FTA            object
FT%           float64
ORB            object
DRB            object
TRB            object
AST            object
STL            object
BLK            object
TOV            object
PF             object
PTS            object
Team           object
dtype: object

Showing the data types of the data set.

In [23]:
data.describe

<bound method NDFrame.describe of     Unnamed: 0     G     MP     FG    FGA     FG%     3P    3PA     3P%  \
0         Team  82.0  19830   3601   7396   0.487   1351   3482   0.388
1       Team/G   NaN  241.8   43.9   90.2   0.487   16.5   42.5   0.388
2      Lg Rank   NaN      7      4      8   8.000      1      1   2.000
3    Year/Year   NaN  -0.8%   4.1%   1.6%   0.011   2.7%  -0.3%   0.011
4     Opponent  82.0  19830   3403   7515   0.453   1059   3008   0.352
5   Opponent/G   NaN  241.8   41.5   91.6   0.453   12.9   36.7   0.352
6      Lg Rank   NaN      7     13     26   2.000     15     23   4.000
7    Year/Year   NaN  -0.8%  -0.6%   1.6%  -0.010  11.0%   8.9%   0.007
8         Team  82.0  19805   3334   7307   0.456   1089   3010   0.362
9       Team/G   NaN  241.5   40.7   89.1   0.456   13.3   36.7   0.362
10     Lg Rank   NaN     10     25     16  28.000      9      9  19.000
11   Year/Year   NaN   0.4%  -1.9%   4.7%  -0.031   3.9%   8.6%  -0.016
12    Opponent  82.0  19805   3410   7255   0.470   1066   2865   0.372
13  Opponent/G   NaN  241.5   41.6   88.5   0.470   13.0   34.9   0.372
14     Lg Rank   NaN     10     14     15  13.000     17     13  22.000
15   Year/Year   NaN   0.4%   1.5%  -0.0%   0.007  10.1%   8.5%   0.005
16        Team  82.0  19730   3385   7272   0.465   1083   2936   0.369
17      Team/G   NaN  240.6   41.3   88.7   0.465   13.2   35.8   0.369
18     Lg Rank   NaN     23     22     18  20.000     10     13  14.000
19   Year/Year   NaN  -1.1%  -1.7%  -0.8%  -0.004   4.4%   0.2%   0.015
20    Opponent  82.0  19730   3304   7026   0.470   1028   2813   0.365
21  Opponent/G   NaN  240.6   40.3   85.7   0.470   12.5   34.3   0.365
22     Lg Rank   NaN     23      4      2  15.000     10     12  17.000
23   Year/Year   NaN  -1.1%  -1.2%  -2.8%   0.008  -3.7%  -6.0%   0.008
24        Team  82.0  19780   3404   7331   0.464    992   2733   0.363
25      Team/G   NaN  241.2   41.5   89.4   0.464   12.1   33.3   0.363
26     Lg Rank   NaN     17     21     14  23.000     22     19  18.000
27   Year/Year   NaN  -0.5%   1.7%   6.7%  -0.023  -4.2%   2.2%  -0.024
28    Opponent  82.0  19780   3322   7098   0.468    979   2765   0.354
29  Opponent/G   NaN  241.2   40.5   86.6   0.468   11.9   33.7   0.354
30     Lg Rank   NaN     17      6      4  11.000      6      7   6.000
31   Year/Year   NaN  -0.5%   0.3%   1.3%  -0.005   2.8%   1.1%   0.006
32        Team  82.0  19805   3466   7356   0.471    942   2712   0.347
33      Team/G   NaN  241.5   42.3   89.7   0.471   11.5   33.1   0.347
34     Lg Rank   NaN     10     15     10  16.000     26     22  27.000
35   Year/Year   NaN   0.0%   0.9%  -1.8%   0.013   7.0%   3.3%   0.012
36    Opponent  82.0  19805   3669   7476   0.491   1120   2979   0.376
37  Opponent/G   NaN  241.5   44.7   91.2   0.491   13.7   36.3   0.376
38     Lg Rank   NaN     10     28     24  26.000     26     21  24.000
39   Year/Year   NaN   0.0%  10.8%  10.7%   0.000  11.9%  11.3%   0.002

       2P  ...     ORB    DRB    TRB    AST     STL     BLK     TOV      PF  \
0    2250  ...     876   2923   3799   2207     557     538     979    1326
1    27.4  ...    10.7   35.6   46.3   26.9     6.8     6.6    11.9    16.2
2      27  ...      14      1      2     14      27       1       1       2
3    4.9%  ...   10.1%   0.1%   2.2%   1.0%    6.9%   25.1%  -10.6%  -14.0%
4    2344  ...     907   2645   3552   2042     510     304     986    1416
5    28.6  ...    11.1   32.3   43.3   24.9     6.2     3.7    12.0    17.3
6      13  ...      26     10     14      5       2       1      29      30
7   -5.1%  ...   13.5%  -5.9%  -1.6%   7.8%   -6.3%   -4.4%   -5.2%   -9.7%
8    2245  ...     938   2675   3613   2102     556     424    1076    1516
9    27.4  ...    11.4   32.6   44.1   25.6     6.8     5.2    13.1    18.5
10     28  ...       7     20     11     20      28      12      12      13
11  -4.5%  ...   39.2%   1.0%   8.8%   0.4%   -5.0%  -16.2%   -4.5%  -12.4%
12   2344  ...     843   2788   3631   2088     563     409    1035    1496
13   28.6  ...    10.3   34.0   44.3   25.5     6.9     5.0    12.6    18.2
14     13  ...       9     24     21      7       8      16      25      21
15  -2.0%  ...  -10.6%   1.1%  -1.9%   9.0%   -2.1%   29.0%   -8.1%   -1.4%
16   2302  ...    1039   2665   3704   1998     612     336    1085    1447
17   28.1  ...    12.7   32.5   45.2   24.4     7.5     4.1    13.2    17.6
18     24  ...       1     21      5     29      17      29      15       6
19  -4.4%  ...    0.8%  -4.5%  -3.1%   6.3%   16.1%   -1.2%    1.9%  -13.1%
20   2276  ...     839   2492   3331   2098     552     431    1082    1565
21   27.8  ...    10.2   30.4   40.6   25.6     6.7     5.3    13.2    19.1
22      6  ...       8      2      2      8       6      20      21      10
23   0.0%  ...    1.1%  -4.8%  -3.4%   1.7%   11.3%   16.5%    3.6%   -7.6%
24   2412  ...     906   2616   3522   2041     694     492     984    1668
25   29.4  ...    11.0   31.9   43.0   24.9     8.5     6.0    12.0    20.3
26     13  ...       9     23     20     24       1       6       2      27
27   4.3%  ...   26.7%  -0.9%   4.9%  -1.1%    9.3%   26.5%  -12.2%   -0.4%
28   2343  ...     903   2742   3645   2143     506     503    1201    1519
29   28.6  ...    11.0   33.4   44.5   26.1     6.2     6.1    14.6    18.5
30     12  ...      25     18     22     10       1      27       4      17
31  -0.7%  ...   15.5%   5.7%   8.0%   7.9%   -6.3%   32.4%    2.6%   -5.5%
32   2524  ...     891   2607   3498   2335     634     388    1147    1509
33   30.8  ...    10.9   31.8   42.7   28.5     7.7     4.7    14.0    18.4
34      5  ...      11     26     23      6      10      19      20      12
35  -1.2%  ...  -14.6%   4.9%  -0.9%  19.1%  -17.9%   -8.5%   20.0%   -8.0%
36   2549  ...     919   2785   3704   2346     595     474    1137    1487
37   31.1  ...    11.2   34.0   45.2   28.6     7.3     5.8    13.9    18.1
38     26  ...      28     23     26     27      13      23      13      22
39  10.3%  ...   21.4%   2.8%   6.9%   9.2%   20.9%   26.1%  -16.8%   -7.3%

      PTS Team
0    9887  BOS
1   120.6  BOS
2       2  BOS
3    2.2%  BOS
4    8957  BOS
5   109.2  BOS
6       5  BOS
7   -2.0%  BOS
8    9050  BRK
9   110.4  BRK
10     25  BRK
11  -2.6%  BRK
12   9287  BRK
13  113.3  BRK
14     15  BRK
15   0.7%  BRK
16   9249  NYK
17  112.8  NYK
18     19  NYK
19  -2.8%  NYK
20   8873  NYK
21  108.2  NYK
22      2  NYK
23  -4.3%  NYK
24   9397  PHI
25  114.6  PHI
26     15  PHI
27  -0.5%  PHI
28   9147  PHI
29  111.5  PHI
30      9  PHI
31   0.6%  PHI
32   9213  TOR
33  112.4  TOR
34     21  TOR
35  -0.4%  TOR
36   9741  TOR
37  118.8  TOR
38     25  TOR
39   6.7%  TOR

[40 rows x 25 columns]>

In [24]:
data.head()
data.tail()

,Unnamed: 0,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Team
35,Year/Year,NaN,0.0%,0.9%,-1.8%,0.013,7.0%,3.3%,0.012,-1.2%,...,-14.6%,4.9%,-0.9%,19.1%,-17.9%,-8.5%,20.0%,-8.0%,-0.4%,TOR
36,Opponent,82.0,19805,3669,7476,0.491,1120,2979,0.376,2549,...,919,2785,3704,2346,595,474,1137,1487,9741,TOR
37,Opponent/G,NaN,241.5,44.7,91.2,0.491,13.7,36.3,0.376,31.1,...,11.2,34.0,45.2,28.6,7.3,5.8,13.9,18.1,118.8,TOR
38,Lg Rank,NaN,10,28,24,26.000,26,21,24.000,26,...,28,23,26,27,13,23,13,22,25,TOR
39,Year/Year,NaN,0.0%,10.8%,10.7%,0.000,11.9%,11.3%,0.002,10.3%,...,21.4%,2.8%,6.9%,9.2%,20.9%,26.1%,-16.8%,-7.3%,6.7%,TOR

First and last 5 rows of the dataset.

In [26]:
data.sample(5)
#data.info()

,Unnamed: 0,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Team
23,Year/Year,NaN,-1.1%,-1.2%,-2.8%,0.008,-3.7%,-6.0%,0.008,0.0%,...,1.1%,-4.8%,-3.4%,1.7%,11.3%,16.5%,3.6%,-7.6%,-4.3%,NYK
3,Year/Year,NaN,-0.8%,4.1%,1.6%,0.011,2.7%,-0.3%,0.011,4.9%,...,10.1%,0.1%,2.2%,1.0%,6.9%,25.1%,-10.6%,-14.0%,2.2%,BOS
17,Team/G,NaN,240.6,41.3,88.7,0.465,13.2,35.8,0.369,28.1,...,12.7,32.5,45.2,24.4,7.5,4.1,13.2,17.6,112.8,NYK
25,Team/G,NaN,241.2,41.5,89.4,0.464,12.1,33.3,0.363,29.4,...,11.0,31.9,43.0,24.9,8.5,6.0,12.0,20.3,114.6,PHI
20,Opponent,82.0,19730,3304,7026,0.470,1028,2813,0.365,2276,...,839,2492,3331,2098,552,431,1082,1565,8873,NYK